# MCU name
MCU = STM32F103

# Bootloader selection
BOARD = STM32_F103_STM32DUINO
BOOTLOADER_TYPE = stm32duino

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
AUDIO_ENABLE = no
NKRO_ENABLED = yes
ENCODER_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLED = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = spi
